(() => {
  "use strict";
  const qs = new URLSearchParams(window.location.search);
  const repositoryAssignments = {
    "crowdcheck-s1-control": {study:1,condition:"control"},
    "crowdcheck-s1-public-note": {study:1,condition:"public_note"},
    "crowdcheck-s2-control": {study:2,condition:"control"},
    "crowdcheck-s2-public-note": {study:2,condition:"public_note"},
    "crowdcheck-s3-control": {study:3,condition:"control"},
    "crowdcheck-s3-few-sources": {study:3,condition:"few_sources"},
    "crowdcheck-s3-many-sources": {study:3,condition:"many_sources"},
    "crowdcheck-s4-control": {study:4,condition:"control"},
    "crowdcheck-s4-moderate-reliability": {study:4,condition:"moderate_reliability"},
    "crowdcheck-s4-high-reliability": {study:4,condition:"high_reliability"}
  };
  const repositoryName=window.location.pathname.split("/").filter(Boolean)[0]||"";
  const repositoryAssignment=repositoryAssignments[repositoryName]||null;
  const defaultStudy=Number(document.body.dataset.defaultStudy||1);
  const requestedStudy=Number(qs.get("study"));
  const study=repositoryAssignment?repositoryAssignment.study:[1,2,3,4].includes(requestedStudy)?requestedStudy:defaultStudy;
  const fixedCondition=repositoryAssignment?.condition||null;
  const participantId=sanitizeId(qs.get("pid"))||createId("P");
  const sessionId=createId("S");
  const returnUrl=qs.get("returnUrl");
  const isDebug=qs.get("debug")==="1";
  const studyConfig={
    1:{topic:"城市散步路线",instruction:"请让AI助手创作一段“周末城市散步路线”分享，内容应轻松、具体，适合发布在社交媒体。",defaultPrompt:"写一段周末城市散步路线分享，语气自然，包含路线、休息点和一个拍照建议。",generated:"周末想放慢脚步，可以试试这条城市散步路线：从老街口出发，沿着河边步道慢慢走，途中在街角咖啡店休息，再到城市公园看日落。全程不赶时间，穿一双舒服的鞋就好。傍晚光线柔和，桥边和树影下都很适合拍照。#周末散步 #城市生活"},
    2:{topic:"学习效率经验",instruction:"请让AI助手创作一段“提高学习效率”经验分享，内容应实用、自然，适合发布在社交媒体。",defaultPrompt:"写一段提高学习效率的经验分享，包含三个容易执行的方法，语气不要说教。",generated:"最近试了三个提高学习效率的小方法：第一，把任务拆成25分钟的小段；第二，开始前只保留当前需要的资料；第三，每完成一段就用一句话记录进度。重点不是把时间排满，而是减少频繁切换。坚持几天后，学习节奏会稳定很多。#学习方法 #效率提升"},
    3:{topic:"周末博物馆攻略",instruction:"请让AI助手创作一段“周末博物馆攻略”，内容应包含参观建议，适合发布在社交媒体。",defaultPrompt:"写一段周末博物馆参观攻略，包含预约、参观顺序和休息建议，语气轻松。",generated:"周末逛博物馆可以提前一天预约，开馆后先看最想去的常设展，再根据体力安排临展。建议每参观一个小时就休息十分钟，重点展品旁的说明可以先拍下来，回家再慢慢看。避开午后高峰，体验通常会更从容。#博物馆攻略 #周末去哪儿"},
    4:{topic:"居家收纳技巧",instruction:"请让AI助手创作一段“居家收纳技巧”分享，内容应简单可执行，适合发布在社交媒体。",defaultPrompt:"写一段居家收纳技巧，包含分类、摆放和定期整理三个建议，语气亲切。",generated:"居家收纳不一定要一次完成，可以从一个抽屉开始：先按使用频率分类，把每天会用的物品放在伸手可及的位置；同类物品尽量集中，避免重复购买；每月留十分钟检查一次，把不再需要的东西及时处理。空间会慢慢变得清爽。#居家整理 #收纳技巧"}
  };
  const conditions={1:["control","public_note"],2:["control","public_note"],3:["control","few_sources","many_sources"],4:["control","moderate_reliability","high_reliability"]};
  const intentionItems=["未来三个月，如果我发布使用生成式AI创作的社交媒体内容，我打算主动添加AI内容声明。","未来三个月，如果我发布这类内容，我计划在发布时说明生成式AI的使用。","未来三个月，如果我发布这类内容，我很可能主动添加AI内容声明。"];
  const reputationItems=["在回答未来是否添加AI声明时，我想到其他用户今后会如何看待我。","其他用户会知道我的做法，这一点影响了我的回答。","我希望确保其他用户会正面评价我。","我没有考虑其他用户会如何谈论或评价我。"];
  const state={participantId,sessionId,study,condition:null,eligibleForRandomization:null,initialDisclosure:null,prompt:"",aiDraft:"",finalDraft:"",aiCalls:0,startedAt:new Date().toISOString(),events:[],responses:{}};
  const $=id=>document.getElementById(id); const config=studyConfig[study];
  function sanitizeId(value){if(!value)return"";return value.replace(/[^a-zA-Z0-9_-]/g,"").slice(0,80)}
  function createId(prefix){const bytes=new Uint32Array(2);crypto.getRandomValues(bytes);return `${prefix}-${Date.now().toString(36)}-${bytes[0].toString(36)}${bytes[1].toString(36)}`}
  function logEvent(name,detail={}){state.events.push({name,at:new Date().toISOString(),elapsedMs:Date.now()-new Date(state.startedAt).getTime(),...detail})}
  function showScreen(id){document.querySelectorAll(".screen").forEach(screen=>screen.classList.toggle("active",screen.id===id));window.scrollTo({top:0,behavior:"smooth"});logEvent("screen_view",{screen:id})}
  function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
  function renderLikert(containerId,prefix,items){const container=$(containerId);container.innerHTML="";items.forEach((item,index)=>{const wrapper=document.createElement("div");wrapper.className="likert-item";wrapper.innerHTML=`<p>${index+1}. ${escapeHtml(item)}</p>`;const scale=document.createElement("div");scale.className="likert-scale";scale.setAttribute("role","radiogroup");scale.setAttribute("aria-label",item);for(let value=1;value<=7;value+=1){const label=document.createElement("label");label.innerHTML=`<input type="radio" name="${prefix}_${index+1}" value="${value}" required><span>${value}</span>`;scale.appendChild(label)}wrapper.appendChild(scale);wrapper.insertAdjacentHTML("beforeend",'<div class="scale-anchors"><span>非常不同意</span><span>非常同意</span></div>');container.appendChild(wrapper)})}
  function renderChecks(){const container=$("manipulation-items");const items=[["visibility_check","刚才页面中的社区附注是向所有浏览者公开显示的。"],["crowd_source_check","刚才的附注反映了多名社区贡献者的判断。"],["realism_check","我能想象类似情景出现在现实社交媒体平台中。"]];if(study===3)items.splice(2,0,["quantity_check","我感觉有较多相互独立的用户参与了这次核查。"]);if(study===4)items.splice(2,0,["reliability_check","参与核查的贡献者具有可靠的历史判断记录。"]);container.innerHTML="";items.forEach(([name,text],index)=>{const wrapper=document.createElement("fieldset");wrapper.innerHTML=`<legend>${index+1}. ${escapeHtml(text)}</legend>`;const scale=document.createElement("div");scale.className="likert-scale";for(let value=1;value<=7;value+=1){const label=document.createElement("label");label.innerHTML=`<input type="radio" name="${name}" value="${value}" required><span>${value}</span>`;scale.appendChild(label)}wrapper.appendChild(scale);wrapper.insertAdjacentHTML("beforeend",'<div class="scale-anchors"><span>非常不同意</span><span>非常同意</span></div>');container.appendChild(wrapper)})}
  function chooseCondition(){if(fixedCondition&&conditions[study].includes(fixedCondition))return fixedCondition;const requested=qs.get("condition");if(requested&&conditions[study].includes(requested))return requested;const bytes=new Uint32Array(1);crypto.getRandomValues(bytes);return conditions[study][bytes[0]%conditions[study].length]}
  function noteMetadata(condition){if(condition==="few_sources")return"评价信息：共有5名相互独立的社区贡献者参与评价，其中4名认为这条附注有帮助。";if(condition==="many_sources")return"评价信息：共有30名相互独立的社区贡献者参与评价，其中24名认为这条附注有帮助。";if(condition==="moderate_reliability")return"评价信息：共有30名相互独立的社区贡献者参与评价，其中24名认为这条附注有帮助。参与评价的贡献者过往评价平均有70%与社区最终核查结果一致。";if(condition==="high_reliability")return"评价信息：共有30名相互独立的社区贡献者参与评价，其中24名认为这条附注有帮助。参与评价的贡献者过往评价平均有90%与社区最终核查结果一致。";return""}
  function displayPublishedPost(){$("published-content").textContent=state.finalDraft;$("ai-label").hidden=!state.initialDisclosure;const hasNote=state.eligibleForRandomization&&state.condition!=="control";$("community-note").hidden=!hasNote;const metadata=noteMetadata(state.condition);$("note-metadata").hidden=!metadata;$("note-metadata").textContent=metadata;$("initial-discloser-exit").hidden=!state.initialDisclosure;$("continue-panel").hidden=Boolean(state.initialDisclosure);showScreen("post-screen");logEvent("post_rendered",{initialDisclosure:state.initialDisclosure,eligibleForRandomization:state.eligibleForRandomization,condition:state.condition,noteVisible:hasNote})}
  function serializeForm(form){return Object.fromEntries(new FormData(form).entries())}
  function applyCorrection(){const correction=state.responses.survey?.correction;if(correction!=="add")return;$("ai-label").hidden=false;$("note-repaired").hidden=false;logEvent("simulated_correction_applied")}
  function finishExperiment(path){state.completedAt=new Date().toISOString();state.completionPath=path;state.completionCode=`WG-${study}-${sessionId.slice(-8).toUpperCase()}`;logEvent("experiment_complete",{path});const storageKey=`crowdchecking-${sessionId}`;try{localStorage.setItem(storageKey,JSON.stringify(state))}catch(_){state.storageWarning=true}window.parent?.postMessage({type:"crowdchecking-experiment-complete",payload:state},"*");$("completion-code").textContent=`完成码：${state.completionCode}`;if(returnUrl)$("return-btn").hidden=false;showScreen("complete-screen")}
  function generateDraft(){const prompt=$("prompt-input").value.trim();if(prompt.length<5){$("prompt-input").focus();$("prompt-input").setCustomValidity("请先输入至少5个字的提示词。");$("prompt-input").reportValidity();return}$("prompt-input").setCustomValidity("");state.prompt=prompt;state.aiCalls+=1;logEvent("ai_generation_requested",{call:state.aiCalls,promptLength:prompt.length});$("generate-btn").disabled=true;$("ai-working").hidden=false;window.setTimeout(()=>{const lead=prompt.includes("第一人称")?"我整理了一条适合周末实践的分享。":"";state.aiDraft=`${lead}${lead?"\n\n":""}${config.generated}`;$("draft-input").value=state.aiDraft;$("draft-panel").hidden=false;$("ai-working").hidden=true;$("generate-btn").disabled=false;updateCount($("draft-input"),$("draft-count"),1500);logEvent("ai_generation_completed",{call:state.aiCalls,outputLength:state.aiDraft.length});$("draft-panel").scrollIntoView({behavior:"smooth",block:"start"})},700)}
  function updateCount(input,output,limit){output.textContent=`${input.value.length} / ${limit}`}
  $("topic-instruction").textContent=`本次主题：${config.topic}。${config.instruction}`;$("prompt-input").value=config.defaultPrompt;updateCount($("prompt-input"),$("prompt-count"),500);renderLikert("intention-items","intention",intentionItems);renderLikert("reputation-items","reputation",reputationItems);renderChecks();$("reputation-fieldset").hidden=study===1;
  $("consent").addEventListener("change",event=>{$("start-btn").disabled=!event.target.checked});$("start-btn").addEventListener("click",()=>{logEvent("consent_confirmed");showScreen("create-screen")});$("prompt-input").addEventListener("input",()=>updateCount($("prompt-input"),$("prompt-count"),500));$("draft-input").addEventListener("input",()=>updateCount($("draft-input"),$("draft-count"),1500));$("generate-btn").addEventListener("click",generateDraft);
  $("to-publish-btn").addEventListener("click",()=>{const finalDraft=$("draft-input").value.trim();if(finalDraft.length<20){$("draft-input").setCustomValidity("最终文案请至少保留20个字。");$("draft-input").reportValidity();return}$("draft-input").setCustomValidity("");state.finalDraft=finalDraft;state.editDistanceApprox=Math.abs(state.aiDraft.length-finalDraft.length);logEvent("draft_confirmed",{finalLength:finalDraft.length,aiLength:state.aiDraft.length,approximateLengthChange:state.editDistanceApprox});$("publish-text").value=finalDraft;showScreen("publish-screen")});$("publish-text").addEventListener("input",event=>{state.finalDraft=event.target.value});
  $("publish-btn").addEventListener("click",()=>{const finalDraft=$("publish-text").value.trim();if(finalDraft.length<20){$("publish-text").setCustomValidity("发布文案请至少保留20个字。");$("publish-text").reportValidity();return}state.finalDraft=finalDraft;state.initialDisclosure=$("initial-disclosure").checked;state.eligibleForRandomization=!state.initialDisclosure;state.condition=state.eligibleForRandomization?chooseCondition():"initial_discloser";logEvent("initial_publish_submitted",{initialDisclosure:state.initialDisclosure,eligibleForRandomization:state.eligibleForRandomization,assignedCondition:state.condition});displayPublishedPost()});
  $("initial-finish-btn").addEventListener("click",()=>finishExperiment("initial_discloser"));$("to-survey-btn").addEventListener("click",()=>showScreen("survey-screen"));$("survey-form").addEventListener("submit",event=>{event.preventDefault();state.responses.survey=serializeForm(event.currentTarget);logEvent("primary_outcomes_submitted",{correction:state.responses.survey.correction});applyCorrection();showScreen("checks-screen")});$("checks-form").addEventListener("submit",event=>{event.preventDefault();state.responses.checks=serializeForm(event.currentTarget);logEvent("manipulation_checks_submitted",{attentionCheck:state.responses.checks.attention_check});finishExperiment("randomized_experiment")});
  $("return-btn").addEventListener("click",()=>{const target=new URL(returnUrl);target.searchParams.set("completionCode",state.completionCode);target.searchParams.set("pid",participantId);window.location.href=target.toString()});
  if(isDebug){$("debug-panel").hidden=false;$("debug-study").value=String(study);$("debug-study").addEventListener("change",event=>{const target=new URL(window.location.href);target.searchParams.set("study",event.target.value);target.searchParams.set("debug","1");window.location.href=target.toString()});$("debug-condition").textContent=fixedCondition?`固定条件：${fixedCondition}`:`可用条件：${conditions[study].join(" / ")}`}
  logEvent("experiment_loaded",{study,participantId,forcedCondition:fixedCondition||qs.get("condition")||null,referrerPresent:Boolean(document.referrer)});
})();
